name: terraform apply

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533266981533:role/portfolio-web_cicd_apply_role
          aws-region: ap-northeast-1

      - uses: hashicorp/setup-terraform@v3

      - run: |
         terraform init \
            -backend-config="bucket=tf-portfolio-state-533266981533-ap-northeast-1-an" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=ap-northeast-1"
      - run: terraform apply -auto-approve